Repository NKUST-ITC/NKUST-AP-Flutter, pull requests merged in 2020-08, with the labels that each got.

#115 校務系統爬蟲
  lib/api/ap_helper.dart
  lib/api/ap_status_code.dart
  lib/api/helper.dart
  lib/api/parser/ap_parser.dart
  lib/api/private_cookie_manager.dart
  lib/config/constants.dart
  lib/pages/home_page.dart
  lib/pages/login_page.dart
Labels: enhancement

#116 校車系統爬蟲
  lib/api/bus_helper.dart
  lib/api/helper.dart
  lib/api/parser/bus_parser.dart
  lib/models/bus_data.dart
  lib/models/bus_reservations_data.dart
  lib/models/bus_violation_records_data.dart
Labels: enhancement

#118 Web ap logout and clear setting
  lib/api/ap_helper.dart
  lib/api/helper.dart
Labels: bug

#120 Update getNotifications by NKUSTHelper
  lib/api/helper.dart
  lib/api/nkust_helper.dart
  lib/api/parser/nkust_parser.dart
Labels: enhancement

#124 FIx timeTable query lost cancelKey
  lib/api/bus_helper.dart
  lib/api/parser/bus_parser.dart
Labels: bug, crawler

#121 getLeaves by LeaveHelper
  lib/api/helper.dart
  lib/api/leave_helper.dart
  lib/api/parser/leave_parser.dart
Labels: enhancement

#125 Fix check login state and re-try method
  lib/api/ap_helper.dart
  lib/api/bus_helper.dart
  lib/api/helper.dart
Labels: bug, crawler

#127 AP and bus API cache data on HTTP layer
  lib/api/ap_helper.dart
  lib/api/bus_helper.dart
  lib/api/helper.dart
  lib/api/parser/api_tool.dart
  pubspec.yaml
Labels: crawler, enhancement

#129 feature leave submit & submit info
  lib/api/helper.dart
  lib/api/leave_helper.dart
  lib/api/parser/leave_parser.dart
  lib/pages/leave/pick_tutor_page.dart
Labels: crawler, enhancement

#134 處理課程名稱 Transfer-Encoding 未被parse的資料
  lib/api/parser/ap_parser.dart
Labels: bug, crawler

#135 處理 Transfer-Encoding 未被parse的資料(bytes parser)
  lib/api/ap_helper.dart
  lib/api/parser/ap_parser.dart
Labels: bug, crawler

#141 Fix course table startTime and endTime format error
  lib/api/parser/ap_parser.dart
Labels: bug, crawler

#145 修復getNotification 沒有回傳
  lib/api/nkust_helper.dart
Labels: bug, crawler

#147 修復課表消失的13節
  lib/api/parser/ap_parser.dart
Labels: bug, crawler
